/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2024-09-29 16:22:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Tam.CGioHang;

public final class DatHang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Tam.CGioHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form method='post' action ='DatHang.jsp'>\r\n");
      out.write("\t Ten hang <input type='text' name='txtth'><br>\r\n");
      out.write("\t Gia <input type='text' name='txtgia'><br>\r\n");
      out.write("\t So luong <input type='text' name='txtsl'><br>\r\n");
      out.write("\t<input type='submit' name='un1' value='Dat Hang'>\r\n");
      out.write("\t</form>\r\n");
      out.write("Gio hang\r\n");
      out.write("\r\n");

 
	String th = request.getParameter("txtth");
	String gia = request.getParameter("txtgia");
	String sl = request.getParameter("txtsl");
	CGioHang g = (CGioHang) session.getAttribute("gh");
	
	// Náº¿u giá» hÃ ng trá»ng thÃ¬ táº¡o má»i
	if (g == null) {
	    g = new CGioHang();
	    session.setAttribute("gh", g);
	}
	
	// ThÃªm hÃ ng vÃ o giá»
	if (th != null && gia != null && sl != null) {
	    g.Them(th, Integer.parseInt(gia), Integer.parseInt(sl));
	    session.setAttribute("gh", g);
	}
 
 	
 	//XÃ³a cÃ¡c máº·t hÃ ng ÄÃ£ chá»n

 	 String[] itemsToDelete = request.getParameterValues("items");
 	 if (itemsToDelete != null) {
 	     for (String tenHang : itemsToDelete) {
 	         for (int i = 0; i < g.ds.size(); i++) {
 	             if (g.ds.get(i).getTenhang().equals(tenHang)) {
 	                 g.ds.remove(i);
 	                 break;
 	             }
 	         }
 	     }
 	 }

 	 // XÃ³a toÃ n bá» giá» hÃ ng
 	 String action = request.getParameter("action");
 	 if ("deleteAll".equals(action)) {
 	     g.ds.clear();
 	 }

 	 session.setAttribute("gh", g);
 	 

      out.write('\r');
      out.write('\n');
 
//Hien thi do trong session: gh

  if (g.ds.size() > 0) { 
      out.write("\r\n");
      out.write(" <form method=\"post\" action=\"DatHang.jsp\">\r\n");
      out.write("     <table border=\"1\" width=\"100%\">\r\n");
      out.write("         <tr>\r\n");
      out.write("             <th>Chon</th>\r\n");
      out.write("             <th>Ten Hang</th>\r\n");
      out.write("             <th>Gia</th>\r\n");
      out.write("             <th>So Luong</th>\r\n");
      out.write("             <th>Thanh Tien</th>\r\n");
      out.write("             \r\n");
      out.write("         </tr>\r\n");
      out.write("         ");
 for (int i = 0; i < g.ds.size(); i++) { 
      out.write("\r\n");
      out.write("             <tr>\r\n");
      out.write("                 <td><input type=\"checkbox\" name=\"items\" value=\"");
      out.print( g.ds.get(i).getTenhang() );
      out.write("\"></td>\r\n");
      out.write("                 <td>");
      out.print( g.ds.get(i).getTenhang() );
      out.write("</td>\r\n");
      out.write("                 <td>");
      out.print( g.ds.get(i).getGia() );
      out.write("</td>\r\n");
      out.write("                 <td>");
      out.print( g.ds.get(i).getSoluong() );
      out.write("</td>\r\n");
      out.write("                 <td>");
      out.print( g.ds.get(i).getThanhtien() );
      out.write("</td>\r\n");
      out.write("                 \r\n");
      out.write("             </tr>\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("     </table>\r\n");
      out.write("     \r\n");
      out.write("     <div align=\"right\">\r\n");
      out.write("         Tong tien: ");
      out.print( g.Tongtien() );
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <!-- NÃºt xÃ³a cÃ¡c máº·t hÃ ng ÄÃ£ chá»n -->\r\n");
      out.write("     <input type=\"submit\" value=\"Xoa cac mat hang da chon\">\r\n");
      out.write("     \r\n");
      out.write("     <!-- NÃºt xÃ³a táº¥t cáº£ máº·t hÃ ng -->\r\n");
      out.write("     <input type=\"submit\" name=\"action\" value=\"deleteAll\" onclick=\"return confirm('Ban co chac muon xoa mat hang?');\">\r\n");
      out.write(" </form>\r\n");
 } else { 
      out.write("\r\n");
      out.write(" <p>Gio hang cua ban dang trong.</p>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
