/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2024-09-16 15:23:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class baitap_005fdangki_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"dangki.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <div id=\"dboxregister\" name=\"dboxregister\" class=\"fancybox\">\r\n");
      out.write("        <div class=\"lblogin\">\r\n");
      out.write("            <div class=\"lbtitle\">\r\n");
      out.write("                <span>ĐĂNG KÝ</span>\r\n");
      out.write("                <img class=\"lbclose\" src=\"images/icons/closefanbox.gif\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"lbbody\">\r\n");
      out.write("                <p class=\"fbold\"><span class=\"iconlogin\">&nbsp;</span>Đăng ký nhanh qua Facebook</p>\r\n");
      out.write("                <div class=\"logfb\">\r\n");
      out.write("                    <img class=\"imgfb\" src=\"loginfb.jpg\" onclick=\"loginFB();\">\r\n");
      out.write("                    <span class=\"arrowtip\">&nbsp;</span>\r\n");
      out.write("                    <div class=\"tipmark\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>Thưởng ngay <span class=\"cred\">50</span> ePoints khi đăng ký mới\r\n");
      out.write("                                &amp; <span class=\"cred\">5</span> ePoints cho mỗi lượt chia sẻ\r\n");
      out.write("                                Facebook</li>\r\n");
      out.write("                            <li>Tích lũy nhiều ePoints khi Upload tài liệu <a rel=\"nofollow\"\r\n");
      out.write("                                    href=\"https://tailieu.vn/gioi-thieu-diem-epoints.html\">&gt;&gt;</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p id=\"pregister6\" name=\"pregister6\" onclick=\"slidedownLogin(6);\"\r\n");
      out.write("                    class=\"logfb fbold arropen\"\r\n");
      out.write("                    style=\"font-weight:700;color:#0080AF;cursor:pointer;\">Đăng ký mới bằng tài khoản\r\n");
      out.write("                    TaiLieu.VN</p>\r\n");
      out.write("                <div id=\"dregister6\" name=\"dregister6\" style=\"display: block;\">\r\n");
      out.write("                    <p>Bạn cần kích hoạt tài khoản qua Email sau khi đăng ký để nhận ngay 50 ePoints\r\n");
      out.write("                        thưởng từ TaiLieu.VN</p>\r\n");
      out.write("                    <div class=\"spacing margintop10\">\r\n");
      out.write("                        <input placeholder=\"Nhập Username\" type=\"text\" name=\"txtUsername_Regis\"\r\n");
      out.write("                            id=\"txtUsername_Regis\" maxlength=\"50\"\r\n");
      out.write("                            class=\"txt295 marginright10 inputtext\" value=\"\" fdprocessedid=\"vic6gv\">\r\n");
      out.write("                        <input placeholder=\"Nhập Họ và Tên\" type=\"text\" id=\"txtFullname_Regis\"\r\n");
      out.write("                            name=\"txtFullname_Regis\" maxlength=\"100\" class=\"txt295 inputtext\"\r\n");
      out.write("                            value=\"\" fdprocessedid=\"gs9lt\">\r\n");
      out.write("                        <div id=\"txtErrorUser_Regis\" name=\"txtErrorUser_Regis\" class=\"errormsg1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"txtErrorFullname_Regis\" name=\"txtErrorFullname_Regis\"\r\n");
      out.write("                            class=\"errormsg2\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"spacing\">\r\n");
      out.write("                        <input placeholder=\"Nhập mật khẩu\" type=\"password\" id=\"txtPassword_Regis\"\r\n");
      out.write("                            name=\"txtPassword_Regis\" maxlength=\"30\"\r\n");
      out.write("                            class=\"txt295 marginright10 fleft inputtext\" value=\"\"\r\n");
      out.write("                            fdprocessedid=\"44k73p\">\r\n");
      out.write("                        <select name=\"txtGender_Regis\" id=\"txtGender_Regis\"\r\n");
      out.write("                            class=\"select75 fleft inputtext\" fdprocessedid=\"m9p56b\">\r\n");
      out.write("                            <option value=\"\">Giới Tính</option>\r\n");
      out.write("                            <option value=\"1\">Nam</option>\r\n");
      out.write("                            <option value=\"0\">Nữ</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div id=\"txtErrorPass_Regis\" name=\"txtErrorPass_Regis\" class=\"errormsg1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"txtErrorGender_Regis\" name=\"txtErrorGender_Regis\"\r\n");
      out.write("                            class=\"errormsg2\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"spacing\">\r\n");
      out.write("                        <input placeholder=\"Nhập lại mật khẩu\" type=\"password\"\r\n");
      out.write("                            id=\"txtCPassword_Regis\" name=\"txtCPassword_Regis\" maxlength=\"30\"\r\n");
      out.write("                            class=\"txt295 marginright10 fleft inputtext\" value=\"\"\r\n");
      out.write("                            fdprocessedid=\"rmnudr\">\r\n");
      out.write("                        <select name=\"txtDay_Regis\" id=\"txtDay_Regis\"\r\n");
      out.write("                            class=\"select75 fleft inputtext\" fdprocessedid=\"9pdqp\">\r\n");
      out.write("                            <option value=\"\">Ngày sinh</option>\r\n");
      out.write("                            <option value=\"1\">1</option>\r\n");
      out.write("                            <option value=\"2\">2</option>\r\n");
      out.write("                            <option value=\"3\">3</option>\r\n");
      out.write("                            <option value=\"4\">4</option>\r\n");
      out.write("                            <option value=\"5\">5</option>\r\n");
      out.write("                            <option value=\"6\">6</option>\r\n");
      out.write("                            <option value=\"7\">7</option>\r\n");
      out.write("                            <option value=\"8\">8</option>\r\n");
      out.write("                            <option value=\"9\">9</option>\r\n");
      out.write("                            <option value=\"10\">10</option>\r\n");
      out.write("                            <option value=\"11\">11</option>\r\n");
      out.write("                            <option value=\"12\">12</option>\r\n");
      out.write("                            <option value=\"13\">13</option>\r\n");
      out.write("                            <option value=\"14\">14</option>\r\n");
      out.write("                            <option value=\"15\">15</option>\r\n");
      out.write("                            <option value=\"16\">16</option>\r\n");
      out.write("                            <option value=\"17\">17</option>\r\n");
      out.write("                            <option value=\"18\">18</option>\r\n");
      out.write("                            <option value=\"19\">19</option>\r\n");
      out.write("                            <option value=\"20\">20</option>\r\n");
      out.write("                            <option value=\"21\">21</option>\r\n");
      out.write("                            <option value=\"22\">22</option>\r\n");
      out.write("                            <option value=\"23\">23</option>\r\n");
      out.write("                            <option value=\"24\">24</option>\r\n");
      out.write("                            <option value=\"25\">25</option>\r\n");
      out.write("                            <option value=\"26\">26</option>\r\n");
      out.write("                            <option value=\"27\">27</option>\r\n");
      out.write("                            <option value=\"28\">28</option>\r\n");
      out.write("                            <option value=\"29\">29</option>\r\n");
      out.write("                            <option value=\"30\">30</option>\r\n");
      out.write("                            <option value=\"31\">31</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select name=\"txtMonth_Regis\" id=\"txtMonth_Regis\"\r\n");
      out.write("                            class=\"select75 fleft inputtext\" fdprocessedid=\"tl46k\">\r\n");
      out.write("                            <option value=\"\">Tháng</option>\r\n");
      out.write("                            <option value=\"1\">1</option>\r\n");
      out.write("                            <option value=\"2\">2</option>\r\n");
      out.write("                            <option value=\"3\">3</option>\r\n");
      out.write("                            <option value=\"4\">4</option>\r\n");
      out.write("                            <option value=\"5\">5</option>\r\n");
      out.write("                            <option value=\"6\">6</option>\r\n");
      out.write("                            <option value=\"7\">7</option>\r\n");
      out.write("                            <option value=\"8\">8</option>\r\n");
      out.write("                            <option value=\"9\">9</option>\r\n");
      out.write("                            <option value=\"10\">10</option>\r\n");
      out.write("                            <option value=\"11\">11</option>\r\n");
      out.write("                            <option value=\"12\">12</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select name=\"txtYear_Regis\" id=\"txtYear_Regis\"\r\n");
      out.write("                            class=\"select75 fleft inputtext\" fdprocessedid=\"txl9t\">\r\n");
      out.write("                            <option value=\"\">Năm</option>\r\n");
      out.write("                            <option value=\"1960\">1960</option>\r\n");
      out.write("                            <option value=\"1961\">1961</option>\r\n");
      out.write("                            <option value=\"1962\">1962</option>\r\n");
      out.write("                            <option value=\"1963\">1963</option>\r\n");
      out.write("                            <option value=\"1964\">1964</option>\r\n");
      out.write("                            <option value=\"1965\">1965</option>\r\n");
      out.write("                            <option value=\"1966\">1966</option>\r\n");
      out.write("                            <option value=\"1967\">1967</option>\r\n");
      out.write("                            <option value=\"1968\">1968</option>\r\n");
      out.write("                            <option value=\"1969\">1969</option>\r\n");
      out.write("                            <option value=\"1970\">1970</option>\r\n");
      out.write("                            <option value=\"1971\">1971</option>\r\n");
      out.write("                            <option value=\"1972\">1972</option>\r\n");
      out.write("                            <option value=\"1973\">1973</option>\r\n");
      out.write("                            <option value=\"1974\">1974</option>\r\n");
      out.write("                            <option value=\"1975\">1975</option>\r\n");
      out.write("                            <option value=\"1976\">1976</option>\r\n");
      out.write("                            <option value=\"1977\">1977</option>\r\n");
      out.write("                            <option value=\"1978\">1978</option>\r\n");
      out.write("                            <option value=\"1979\">1979</option>\r\n");
      out.write("                            <option value=\"1980\">1980</option>\r\n");
      out.write("                            <option value=\"1981\">1981</option>\r\n");
      out.write("                            <option value=\"1982\">1982</option>\r\n");
      out.write("                            <option value=\"1983\">1983</option>\r\n");
      out.write("                            <option value=\"1984\">1984</option>\r\n");
      out.write("                            <option value=\"1985\">1985</option>\r\n");
      out.write("                            <option value=\"1986\">1986</option>\r\n");
      out.write("                            <option value=\"1987\">1987</option>\r\n");
      out.write("                            <option value=\"1988\">1988</option>\r\n");
      out.write("                            <option value=\"1989\">1989</option>\r\n");
      out.write("                            <option value=\"1990\">1990</option>\r\n");
      out.write("                            <option value=\"1991\">1991</option>\r\n");
      out.write("                            <option value=\"1992\">1992</option>\r\n");
      out.write("                            <option value=\"1993\">1993</option>\r\n");
      out.write("                            <option value=\"1994\">1994</option>\r\n");
      out.write("                            <option value=\"1995\">1995</option>\r\n");
      out.write("                            <option value=\"1996\">1996</option>\r\n");
      out.write("                            <option value=\"1997\">1997</option>\r\n");
      out.write("                            <option value=\"1998\">1998</option>\r\n");
      out.write("                            <option value=\"1999\">1999</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div id=\"txtErrorPass2_Regis\" name=\"txtErrorPass2_Regis\" class=\"errormsg1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"txtErrorBirthday_Regis\" name=\"txtErrorBirthday_Regis\"\r\n");
      out.write("                            class=\"errormsg2\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"spacing\">\r\n");
      out.write("                        <input placeholder=\"Nhập địa chỉ Email\" type=\"text\" id=\"txtEmail_Regis\"\r\n");
      out.write("                            name=\"txtEmail_Regis\" maxlength=\"100\"\r\n");
      out.write("                            class=\"txt295 marginright10 fleft inputtext\" value=\"\"\r\n");
      out.write("                            fdprocessedid=\"dj7qkp\">\r\n");
      out.write("                        <select name=\"txtCity_Regis\" id=\"txtCity_Regis\"\r\n");
      out.write("                            class=\"select75 fleft inputtext\" fdprocessedid=\"65fpv\">\r\n");
      out.write("                            <option value=\"\">Tỉnh/TP</option>\r\n");
      out.write("                            <option value=\"76\">An Giang</option>\r\n");
      out.write("                            <option value=\"64\">Bà Rịa Vũng Tàu</option>\r\n");
      out.write("                            <option value=\"281\">Bắc Cạn</option>\r\n");
      out.write("                            <option value=\"240\">Bắc Giang</option>\r\n");
      out.write("                            <option value=\"781\">Bạc Liêu</option>\r\n");
      out.write("                            <option value=\"241\">Bắc Ninh</option>\r\n");
      out.write("                            <option value=\"75\">Bến Tre</option>\r\n");
      out.write("                            <option value=\"650\">Bình Dương</option>\r\n");
      out.write("                            <option value=\"651\">Bình Phước</option>\r\n");
      out.write("                            <option value=\"62\">Bình Thuận</option>\r\n");
      out.write("                            <option value=\"56\">Bình Định</option>\r\n");
      out.write("                            <option value=\"78\">Cà Mau</option>\r\n");
      out.write("                            <option value=\"71\">Cần Thơ</option>\r\n");
      out.write("                            <option value=\"26\">Cao Bằng</option>\r\n");
      out.write("                            <option value=\"59\">Gia Lai</option>\r\n");
      out.write("                            <option value=\"19\">Hà Giang</option>\r\n");
      out.write("                            <option value=\"351\">Hà Nam</option>\r\n");
      out.write("                            <option value=\"4\">Hà Nội</option>\r\n");
      out.write("                            <option value=\"34\">Hà Tây</option>\r\n");
      out.write("                            <option value=\"39\">Hà Tỉnh</option>\r\n");
      out.write("                            <option value=\"320\">Hải Dương</option>\r\n");
      out.write("                            <option value=\"31\">Hải Phòng</option>\r\n");
      out.write("                            <option value=\"18\">Hòa Bình</option>\r\n");
      out.write("                            <option value=\"321\">Hưng Yên</option>\r\n");
      out.write("                            <option value=\"58\">Khánh Hòa</option>\r\n");
      out.write("                            <option value=\"77\">Kiên Giang</option>\r\n");
      out.write("                            <option value=\"60\">Kon Tum</option>\r\n");
      out.write("                            <option value=\"23\">Lai Châu</option>\r\n");
      out.write("                            <option value=\"63\">Lâm Đồng</option>\r\n");
      out.write("                            <option value=\"25\">Lạng Sơn</option>\r\n");
      out.write("                            <option value=\"20\">Lào Cai</option>\r\n");
      out.write("                            <option value=\"72\">Long An</option>\r\n");
      out.write("                            <option value=\"350\">Nam Định</option>\r\n");
      out.write("                            <option value=\"38\">Nghệ An</option>\r\n");
      out.write("                            <option value=\"30\">Ninh Bình</option>\r\n");
      out.write("                            <option value=\"68\">Ninh Thuận</option>\r\n");
      out.write("                            <option value=\"901\">Nơi khác</option>\r\n");
      out.write("                            <option value=\"210\">Phú Thọ</option>\r\n");
      out.write("                            <option value=\"57\">Phú Yên</option>\r\n");
      out.write("                            <option value=\"52\">Quảng Bình</option>\r\n");
      out.write("                            <option value=\"510\">Quảng Nam</option>\r\n");
      out.write("                            <option value=\"55\">Quảng Ngãi</option>\r\n");
      out.write("                            <option value=\"33\">Quảng Ninh</option>\r\n");
      out.write("                            <option value=\"53\">Quảng Trị</option>\r\n");
      out.write("                            <option value=\"79\">Sóc Trăng</option>\r\n");
      out.write("                            <option value=\"22\">Sơn La</option>\r\n");
      out.write("                            <option value=\"66\">Tây Ninh</option>\r\n");
      out.write("                            <option value=\"36\">Thái Bình</option>\r\n");
      out.write("                            <option value=\"280\">Thái Nguyên</option>\r\n");
      out.write("                            <option value=\"37\">Thanh Hóa</option>\r\n");
      out.write("                            <option value=\"54\">Thừa Thiên Huế</option>\r\n");
      out.write("                            <option value=\"73\">Tiền Giang</option>\r\n");
      out.write("                            <option value=\"8\">TP.HCM</option>\r\n");
      out.write("                            <option value=\"74\">Trà Vinh</option>\r\n");
      out.write("                            <option value=\"27\">Tuyên Quang</option>\r\n");
      out.write("                            <option value=\"70\">Vĩnh Long</option>\r\n");
      out.write("                            <option value=\"211\">Vĩnh Phúc</option>\r\n");
      out.write("                            <option value=\"29\">Yên Bái</option>\r\n");
      out.write("                            <option value=\"511\">Đà Nẵng</option>\r\n");
      out.write("                            <option value=\"50\">Đắc Lắc</option>\r\n");
      out.write("                            <option value=\"1042\">Đắc Nông</option>\r\n");
      out.write("                            <option value=\"900\">Điện Biên</option>\r\n");
      out.write("                            <option value=\"61\">Đồng Nai</option>\r\n");
      out.write("                            <option value=\"67\">Đồng Tháp</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div id=\"txtErrorLoginEmail_Regis\" name=\"txtErrorLoginEmail_Regis\"\r\n");
      out.write("                            class=\"errormsg1\"></div>\r\n");
      out.write("                        <div id=\"txtErrorCity_Regis\" name=\"txtErrorCity_Regis\" class=\"errormsg2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"spacing\">\r\n");
      out.write("                        <input placeholder=\"Nhập lại địa chỉ Email\" type=\"text\" id=\"txtCEmail_Regis\"\r\n");
      out.write("                            name=\"txtCEmail_Regis\" maxlength=\"100\"\r\n");
      out.write("                            class=\"txt295 marginright10 fleft inputtext\" value=\"\"\r\n");
      out.write("                            fdprocessedid=\"1u7qi8\">\r\n");
      out.write("                        <input placeholder=\"Nhập mã xác nhận\" type=\"text\" id=\"txtCaptcha_Regis\"\r\n");
      out.write("                            name=\"txtCaptcha_Regis\" maxlength=\"30\"\r\n");
      out.write("                            class=\"txt295 marginright10 fleft inputtext\" style=\"width:120px;\"\r\n");
      out.write("                            value=\"\" fdprocessedid=\"r56lfq\">\r\n");
      out.write("                        <span id=\"spmImgCaptcha_Regis\" name=\"spmImgCaptcha_Regis\" class=\"fleft\"><img\r\n");
      out.write("                                src=\"https://tailieu.vn/image/captcha/6c5e65b29715f3866525603694d0179f.png\"></span>\r\n");
      out.write("                        <input type=\"hidden\" value=\"6c5e65b29715f3866525603694d0179f\"\r\n");
      out.write("                            name=\"captcha_id_Regis\" id=\"captcha_id_Regis\">\r\n");
      out.write("                        <a onclick=\"changeCaptchaLogin_Regis();\" href=\"javascript:void(0);\"\r\n");
      out.write("                            class=\"newcap fleft\">Chọn mã xác nhận khác.</a>\r\n");
      out.write("                        <div id=\"txtErrorLoginEmail2_Regis\" name=\"txtErrorLoginEmail2\"\r\n");
      out.write("                            class=\"errormsg1\"></div>\r\n");
      out.write("                        <div id=\"txtErrorDKCode_Regis\" name=\"txtErrorDKCode\" class=\"errormsg2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"clear\"></div>\r\n");
      out.write("                    <div class=\"margintop5 \">\r\n");
      out.write("                            <div class=\"btncenterblue\">\r\n");
      out.write("                                <span class=\"btntext\">Đăng ký</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"fleft marginleft6 paddingtop10\">\r\n");
      out.write("                            <input checked=\"checked\" type=\"checkbox\" name=\"chkRight_Regis\"\r\n");
      out.write("                                id=\"chkRight_Regis\" value=\"1\">&nbsp;Tôi đồng ý với các Chính Sách và\r\n");
      out.write("                            Thỏa Thuận Sử Dụng của TaiLieu.VN\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"clear\"></div>\r\n");
      out.write("                    <span style=\"border-bottom:1px dashed #cecece;width:750px;float:left;\"></span>\r\n");
      out.write("                    <p id=\"plogin5\" name=\"plogin5\" \r\n");
      out.write("                   \r\n");
      out.write("                    style=\"font-weight:700;color:#0080AF;cursor:pointer;\">Bạn đã có tài khoản\r\n");
      out.write("                    TaiLieu.VN? Đăng nhập</p>\r\n");
      out.write("              \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"lbbottom\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p>Thưởng <span class=\"fxanh1 fbold\">50</span> ePoints khi đăng ký mới\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p>Tặng <span class=\"fxanh1 fbold\">5</span> ePoints cho mỗi lượt chia sẻ\r\n");
      out.write("                                Facebook</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p>Xem và Tải trên <span class=\"fxanh1 fbold\">1 Triệu</span> Tài Liệu\r\n");
      out.write("                                miễn phí</p>\r\n");
      out.write("                            <p>Kết nối <span class=\"fxanh1 fbold\">5 Triệu</span> Thành Viên <a\r\n");
      out.write("                                    href=\"https://tailieu.vn/\">TaiLieu.VN</a> </p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"btlast\">\r\n");
      out.write("                            <div style=\"width:210px;\">\r\n");
      out.write("                                <div class=\"left\" style=\"margin-bottom:5px;\">Kết bạn với <b><a\r\n");
      out.write("                                            target=\"_blank\"\r\n");
      out.write("                                            href=\"https://www.facebook.com/tailieu.vn\">TaiLieu.VN</a></b>\r\n");
      out.write("                                    trên <b><a target=\"_blank\"\r\n");
      out.write("                                            href=\"https://www.facebook.com/tailieu.vn\">Facebook</a></b>\r\n");
      out.write("                                    để nhận link download miễn phí <span class=\"cred\">100</span> tài\r\n");
      out.write("                                    liệu <span class=\"cred\">HOT</span> mỗi ngày</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
